name:  Integraçao Continua e Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Check out Code
         uses: actions/checkout@v2

      #  - name: Configuracao .Net 6
      #    uses: actions/checkout@v2
      #    with:
      #      dotnet-version: '6.0.x'

       - name: Setup .NET 6.0
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 6.0.x           

       - name: Restore dependencies 
         run: dotnet dotnet restore ./security.api/security.api.csproj 

       - name: Build app 
         run: dotnet build ./security.api/security.api.sln  --configuration Release --no-restore



